export { default as Hero } from "./Hero"
export { default as Background } from "./Background"
export { default as Technologies } from "./Technologies"
export { default as Timeline } from "./Timeline"
export { default as Projects } from "./projects/Projects"
export { default as Footer } from "./Footer"
export { default as Layout } from "./Layout"
